# Site settings
title: 首页
email: devgis@163.com
description: Hello World!用程序改变世界！
baseurl: / # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: devgis
github_username:  devgis

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 20
paginate_path: "/page:num"


collections:
  homes:
    output: true
    permalink: /homes/:path

